feat: basic ip summary
diego-aquino/abuse-ip-angular pull request #3
Opened 2024-09-13 15:21 UTC by finalcontradiction

https://github.com/user-attachments/assets/afa3aa7c-14e6-4740-aedb-e4600aa0506e

2024-09-14 13:23 UTC, diego-aquino requested changes
Muito bom! Apenas duas sugestões.

2024-09-14 13:23 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.error);
Podemos remover estes logs?

2024-09-14 13:23 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +      return d.toLocaleDateString('en-GB');
Deveria ser pt-BR aqui?
```suggestion
      return d.toLocaleDateString('pt-BR');
```

2024-09-14 13:23 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +    ]),
Legal!

2024-09-17 00:46 UTC, finalcontradiction commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.error);
Feito!

2024-09-17 01:29 UTC, diego-aquino approved these changes

2024-09-17 13:05 UTC, merged