Add recent reports
diego-aquino/abuse-ip-angular pull request #5
Opened 2024-09-15 17:47 UTC by Daviiap

2024-09-16 14:04 UTC, diego-aquino requested changes

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.ts
> +        console.log(this.summary);
Podemos remover este log?
```suggestion
```

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.ts
> +        console.log(this.error);
Podemos remover este log?
```suggestion
```

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.ts
> +  getTextColor(num: number): string {
Esse método é usado?

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.html
> +  }
Acho que essa parte já é mostrada no componente do IP summary. Se o IP não for encontrado aqui, acho que podemos apenas não mostrar a lista.

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.html
> +      <h1 class="font-medium text-xl">Denúnicias</h1>
```suggestion
      <h1 class="font-medium text-xl">Denúncias</h1>
```

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.html
> +        @for (report of summary.reports; let i = $index; track i) {
```suggestion
        @for (report of summary.reports; let i = $index; track report.reporterId) {
```

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.html
> +            </div>
Tem alguns textos cortando quando são longos. O que acha de usar estes estilos?

```suggestion
            <span matListItemLine><b>Relator</b>: {{ report.reporterId }}</span>
            <span matListItemLine><b>Data</b>: {{ getDate(report.reportedAt) }}</span>
            <span matListItemLine class="max-w-full !whitespace-normal !break-all">
              <b>Comentário</b>:
              {{ report.comment }}
            </span>
            <span matListItemLine><b>Categorias</b>: {{ report.categories.join(', ') }}</span>
```

2024-09-16 14:04 UTC, diego-aquino commented on src/app/components/home/components/ip-reports/ip-reports.component.html
> +            </div>
Antes:
![Screenshot from 2024-09-16 11-02-31](https://github.com/user-attachments/assets/03dd127e-455b-4a1e-9291-a514e24868b0)

Depois:
![Screenshot from 2024-09-16 11-02-05](https://github.com/user-attachments/assets/b94e64cd-c655-4518-97f3-cfd8ba29f4e9)

2024-09-17 02:19 UTC, Daviiap commented on src/app/components/home/components/ip-reports/ip-reports.component.html
> +        @for (report of summary.reports; let i = $index; track i) {
Nesse caso, o reportedID não é uma boa usar, pq ele se repete entre vários reports. E como os reports por sí não tem ID eu coloquei o próprio i pra ser o tracker

2024-09-17 10:58 UTC, diego-aquino approved these changes

2024-09-17 14:17 UTC, merged