Add blacklist alert
diego-aquino/abuse-ip-angular pull request #6
Opened 2024-09-16 03:51 UTC by Iagohss

- Tava com problemas na estilização e acabei usando css via ngStyle. Se isso for um problema, comenta na revisão PR q eu ajeito

2024-09-16 13:33 UTC, diego-aquino requested changes
Ficou bom com o `ngStyle`. Comentei apenas algumas sugestões em outras partes.

2024-09-16 13:33 UTC, diego-aquino commented on src/environments/environment.development.ts
> +  abuseIpApiKey: '5780de24e44ccd5416a7e8ec55b1df235c88ee470e97e7f2024827669e9f6b8cdcd44a03a8eef901',
Pode remover esta key? Não devemos commitá-la.

```suggestion
  abuseIpApiKey: '',
```

2024-09-16 13:33 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.blacklist);
Podemos remover esse log?

2024-09-16 13:33 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.error);
Podemos remover esse log?

2024-09-16 13:33 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.isBlacklisted);
Podemos remover esse log?

2024-09-16 13:33 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.html
> +        <p class="font-medium text-xl text-center">IP não encontrado :</p>
```suggestion
        <p class="font-medium text-xl text-center">IP não encontrado :(</p>
```

2024-09-16 13:35 UTC, diego-aquino commented
Está com alguns conflitos depois das mudanças nos outros PRs. Poderia dar uma olhada?

2024-09-16 22:34 UTC, Iagohss commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.blacklist);
Esse da blacklist é meio necessário, por que os IPs na blacklist mudam de tempos em tempos. Então na hora da apresentação, caso precisarmos pegar um IP que esteja na blacklist este log pode ser útil

2024-09-16 22:37 UTC, Iagohss commented on src/app/components/home/components/ip-summary/ip-summary.component.html
> +        <p class="font-medium text-xl text-center">IP não encontrado :</p>
tava cm sono e achei q era um parênteses não fechado kkkk

2024-09-16 23:17 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.blacklist);
Dá para ver quais IPs foram retornados pela aba Network do navegador também, né? (Eu peguei um blacklisted assim para testar :smile:)

2024-09-16 23:21 UTC, Iagohss commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +        console.log(this.blacklist);
Depende do IP, imagino que alguns que sejam constantemente reportados, provavelmente vão se manter na blacklist. Mas na documentação da API fala que a Blacklist é atualizada de tempos em tempos. Então pode ocorrer de tu pegar um ele não estar mais na blacklist. De toda forma, vou remover esse log. Qualquer coisa a gente dá um log antes da apresentação e copia um ip

2024-09-17 01:33 UTC, diego-aquino commented on src/app/components/home/components/ip-summary/ip-summary.component.html
> +        <p class="font-medium text-xl text-center">IP não encontrado :</p>
Kkkk boa

2024-09-17 01:33 UTC, diego-aquino approved these changes

2024-09-17 14:33 UTC, pedrohenrique-ql requested changes

2024-09-17 14:33 UTC, pedrohenrique-ql commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +
Pode ver se isso funciona? Creio que usando as funções `pipe` e `map` do RxJS seja mais declarativo e funcional, talvez o professor prefira assim.
```suggestion
  import { map } from 'rxjs';

  getBlacklist() {
    this.service
      .blacklist()
      .pipe(map((data: string) => data.split('\n').filter((ip) => ip.trim() !== '')))
      .subscribe({
        next: (blacklist: string[]) => {
          this.blacklist = blacklist;
        },
        error: (err) => {
          console.log(err);

          this.summary = {} as SummaryObj;

          this.error = {
            val: true,
            msg: err.message,
            code: err.status,
          };
        },
      });
  }
```

2024-09-17 15:09 UTC, Iagohss commented on src/app/components/home/components/ip-summary/ip-summary.component.ts
> +
Testei a apliquei a sugestão

2024-09-17 15:25 UTC, pedrohenrique-ql approved these changes

2024-09-17 18:56 UTC, merged